name: Testes Agendados

on:
  schedule:
    - cron: "*/5 * * * 1-5"

jobs:
  Runtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar o Java 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: maven

      - name: Instalar o Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb

      - uses: nanasess/setup-chromedriver@v2
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: Run test
        run: mvn test -Dtest=RunCucumber -Dbrowser=chrome-ci cluecumber-report:reporting

      - name: Gerar Relatório
        if: always()
        run: mvn test cluecumber-report:reporting

      - name: Arquivar relatório
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-execution
          path: "**/formated-report"

      - name: Enviar notificação Slack
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: testes
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Testes Agendados executados com sucesso! :white_check_mark:'
          SLACK_USERNAME: SUCESSO

      - name: Enviar notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: testes
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: 'Testes Agendados falharam! :x_vermelho:'
          SLACK_USERNAME: FALHA